# Generated by Django 5.2.8 on 2025-12-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('pharmaceutical_forms', '0001_initial'),
        ('routes_of_administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('type_of_medicine', models.CharField(choices=[('REF', 'Medicamento de Referência'), ('GEN', 'Medicamento Genérico'), ('SIM', 'Medicamento Similar')], max_length=50)),
                ('indications', models.TextField(blank=True, null=True)),
                ('presentation', models.CharField(max_length=500)),
                ('active_ingredient', models.CharField(max_length=500)),
                ('concentration', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_care', models.TextField()),
                ('medical_prescription', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('doping_alert', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('precautions_and_warnings', models.TextField(blank=True, null=True)),
                ('adverse_reactions', models.TextField(blank=True, null=True)),
                ('estimated_value', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('validity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturers', models.ManyToManyField(related_name='identification', to='manufacturers.manufacturers')),
                ('pharmaceutical_form', models.ManyToManyField(related_name='identification', to='pharmaceutical_forms.pharmaceuticalforms')),
                ('routes_of_administration', models.ManyToManyField(related_name='identification', to='routes_of_administration.routesofadministration')),
            ],
        ),
    ]
