# Generated by Django 5.2.8 on 2025-12-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_identification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugidentification',
            name='batch_number',
            field=models.CharField(max_length=50,
                                   blank=True,
                                    null=True),
        ),
    ]
