# Generated by Django 5.2.8 on 2025-11-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutesOfAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ENT', 'Enterais'), ('PAR', 'Parenterais(injetáveis)'), ('TOP', 'Tópicos/Locais')], max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
