# Generated by Django 5.2.8 on 2025-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaceuticalForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('SOL', 'Sólidos'), ('LIQ', 'Líquidos'), ('SEM', 'Semissólidos'), ('GAS', 'Gasosos')], max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
